client_config_backend: settings
client_config:
  client_id: 47211743945-lqto573ul0uenn6ghreojg6c499tjdau.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install